name: CI/CD

on:
  pull_request:
  push:
    branches: [ h0tw1r3 ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      re_image: ${{ steps.create-inputs.outputs.re_image }}
      re_tag: ${{ steps.create-inputs.outputs.re_tag }}
      re_dockerfile: ${{ steps.create-inputs.outputs.re_dockerfile }}
      do_build: ${{ steps.create-inputs.outputs.do_build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          json: true
          quotepath: false
      - name: Create inputs
        id: create-inputs
        shell: python {0}
        run: |
          import json
          import os
          import re

          re_image = re_tag = re_dockerfile = ''
          changed_files = json.loads("${{ steps.changed-files.outputs.all_changed_files }}")
          with open('images.json') as fd:
            builds = json.load(fd)

          dockerfiles = list(map(lambda v: v.removesuffix('.dockerfile'), filter(lambda v: re.match('.*dockerfile$', v), changed_files)))
          if len(dockerfiles) > 0:
            re_dockerfile = '(' + '|'.join(dockerfiles) + ')'

          with open(os.environ['GITHUB_OUTPUT'], 'a') as output:
            if re_dockerfile == re_image == re_tag:
              print('do_build=false', file=output)
              print('::notice title=::found no image related changes')
            else:
              print('do_build=true', file=output)
              print(f're_dockerfile={re_dockerfile}', file=output)
              print(f're_image={re_image}', file=output)
              print(f're_tag={re_tag}', file=output)

  build:
    needs: prepare
    if: needs.prepare.outputs.do_build == 'true'
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image: ${{ needs.prepare.outputs.re_image }}
      tag: ${{ needs.prepare.outputs.re_tag }}
      dockerfile: ${{ needs.prepare.outputs.re_dockerfile }}
      refresh: true
